# Generated by Django 4.1.7 on 2023-03-31 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoe_app', '0002_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='budget_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
